version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: .
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    environment:
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A backend.api.tasks worker --loglevel=info
    volumes:
      - ./:/app
    environment:
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=${API_URL}
    ports:
      - "3000:3000"
