service: aline-kb-ingestor-backend

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}

functions:
  api:
    handler: backend/api/main.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      STAGE: ${self:provider.stage}
    timeout: 29
    memorySize: 512 