service: aline-kb-ingestor-backend

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}

functions:
  api:
    handler: backend/api/main.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      STAGE: ${self:provider.stage}
    timeout: 29
    memorySize: 512

package:
  exclude:
    - frontend/**
    - backend/tests/**
    - backend/data/**
    - backend/env/**
    - backend/__pycache__/**
    - .git/**
    - .gitignore
    - README.md
    - node_modules/**
    - "*.log"
  include:
    - backend/requirements.txt
    - backend/__init__.py

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    fileName: backend/requirements.txt
    dockerizePip: true
    slim: true
    dockerImage: public.ecr.aws/sam/build-python3.11:latest
    dockerExtraFiles:
      - /etc/ssl/certs/ca-certificates.crt

 